### ISSUE TITLE
Move this to opencomponents organisation

### ISSUE THREAD

**Issue by matteofigus** [opentable/ruby-oc#15]
https://github.com/opencomponents

We are trying to bring there all the oc related libraries, utilities, submodules.
Anything against moving this one there too?

@todd 

PS
probably wanna do the same for
https://github.com/opentable/sinatra-opencomponents
https://github.com/opentable/opencomponents-rails

**Comment by todd** [comment]
Nope, I'll schedule some time to move all three of the Ruby projects over to the new org.

**Comment by todd** [comment]
Done.
