### ISSUE TITLE
Adding headers to component request

### ISSUE THREAD

**Issue by matteofigus** [opentable/ruby-oc#8]
Either we request `rendered` or `unredered` components, we need a way to send (optionally) any http header to the registry request (apart from `Accept`). 

One example is `Accept-Language` that may be used by component creators to make components to be rendered using the right language (if not explicitly via a parameter), or `User-Agent`, that can be used to detect a browser type and in case provide a "mobile" markup instead of a "desktop" markup.

Obviously, the client should own the `Accept` one - used for getting the proper render type.

I think the main library (this) should allow headers to be sent when calling the request method, while the Rails or Sinatra plugins could have an option to just forward the original request headers to the OC request.

**Comment by todd** [comment]
Sounds good, I'll look into this. I'm probably going to refactor `Component` initialization a little bit since the API is starting to get a little unwieldy with the number of arguments it accepts.

**Comment by matteofigus** [comment]
:+1:
